describe environment and build process (broken)
Works up to make SARndbox. Haven't had time to dig yet; I think
`makefile` needs to be modified to handle envrionment variables (same as
   Vrui and Kinect)

```
hello@sandbox:~/code/SARndbox$ make
VRUI_MAKEDIR=$HOME/sandbox/share/Vrui-3.1/make
makefile:59:
/home/hello/sandbox/share/Vrui-3.1/make/Configuration.Kinect: No such
file or directory
makefile:60: /home/hello/sandbox/share/Vrui-3.1/make/Packages.Kinect: No
such file or directory
Compiling CalibrateProjector.cpp...
In file included from CalibrateProjector.cpp:23:0:
CalibrateProjector.h:42:32: fatal error: Kinect/FrameBuffer.h: No such
file or directory
                                ^
compilation terminated.
/home/hello/sandbox/share/Vrui-3.1/make/BasicMakefile:122: recipe for
target 'o/g++-3.g0.O3/CalibrateProjector.o' failed
make: *** [o/g++-3.g0.O3/CalibrateProjector.o] Error 1

```